import type { TransitionMeta } from '../../shared/types'

/**
 * Ficha de "Aceleración". Datos puros: sin JSX y sin tocar renderer/.
 *
 * Va sincronizada con `assets/audio/aceleracion.mpeg` (15 s): diez segundos de
 * subida y un golpe fuerte al final, que es donde frena y aparece el planeta.
 * Las opciones de `planet` deben coincidir con `WORLD_KINDS`
 * (`renderer/scene/worlds.tsx`).
 */
export const aceleracionMeta: TransitionMeta = {
  id: 'aceleracion',
  name: 'Aceleración',
  description: 'Las estrellas corren cada vez más, la nave frena en seco y un planeta se acerca hasta el destello.',
  from: 'cabina-deriva',
  to: 'cabina-deriva',
  accent: '#ef8a3c',
  looks: ['realista'],
  // Arranca mezclándose con la animación de la que sale.
  showsScenes: true,
  exitFlash: '#ffffff',
  params: [
    {
      kind: 'select',
      key: 'planet',
      label: 'Planeta',
      group: 'Destino',
      preview: 'world',
      options: [
        { value: 'desertico', label: 'Desértico' },
        { value: 'gaseoso', label: 'Gigante gaseoso' },
        { value: 'anillado', label: 'Anillado' },
        { value: 'enano', label: 'Planeta enano' },
        { value: 'oceanico', label: 'Oceánico' },
        { value: 'volcanico', label: 'Volcánico' },
      ],
      default: 'oceanico',
    },
    {
      kind: 'number',
      key: 'planetSize',
      label: 'Tamaño al llegar',
      hint: 'Radio del planeta justo antes del destello. El enano llega a la mitad.',
      group: 'Destino',
      min: 150,
      max: 900,
      step: 10,
      default: 520,
    },
    {
      kind: 'number',
      key: 'durationMs',
      label: 'Duración',
      hint: 'Ajustada al audio (15 s). Si la cambias, la imagen deja de ir a tiempo con el sonido.',
      group: 'Ritmo',
      min: 6000,
      max: 30000,
      step: 100,
      unit: ' ms',
      default: 15000,
    },
    {
      kind: 'number',
      key: 'startSpeed',
      label: 'Velocidad inicial',
      hint: 'Igual que la velocidad de crucero de la deriva, para que el arranque no dé salto',
      group: 'Ritmo',
      min: 0,
      max: 3,
      step: 0.05,
      unit: 'x',
      default: 1,
    },
    {
      kind: 'number',
      key: 'warp',
      label: 'Velocidad máxima',
      group: 'Ritmo',
      min: 2,
      max: 8,
      step: 0.1,
      unit: 'x',
      default: 5,
    },
    {
      kind: 'number',
      key: 'shake',
      label: 'Temblor',
      hint: 'A 0 la cabina queda firme',
      group: 'Ritmo',
      min: 0,
      max: 2,
      step: 0.05,
      unit: 'x',
      default: 1,
    },
    {
      kind: 'number',
      key: 'mixInMs',
      label: 'Mezcla de entrada',
      hint: 'La animación en pantalla se desvanece mientras aparece la cabina',
      group: 'Entrada',
      min: 300,
      max: 5000,
      step: 100,
      unit: ' ms',
      default: 1500,
    },
    {
      kind: 'number',
      key: 'flashOutMs',
      label: 'Salida del destello',
      hint: 'Lo que tarda la animación de destino en aparecer desde el blanco',
      group: 'Destello',
      min: 0,
      max: 3000,
      step: 50,
      unit: ' ms',
      default: 900,
    },
    {
      kind: 'number',
      key: 'volume',
      label: 'Volumen',
      group: 'Audio',
      min: 0,
      max: 1,
      step: 0.05,
      default: 1,
    },
    {
      kind: 'number',
      key: 'starCount',
      label: 'Estrellas',
      hint: 'Igual que la densidad de la deriva',
      group: 'Fuera',
      min: 20,
      max: 400,
      step: 10,
      default: 160,
    },
    {
      kind: 'boolean',
      key: 'leavePlanet',
      label: 'Planeta de la deriva',
      hint: 'El planeta que se ve al arrancar queda atrás al acelerar',
      group: 'Fuera',
      default: true,
    },
  ],
}
