import type { TransitionMeta } from '../../shared/types'

/** Ficha de "Encendido de cabina". Datos puros: sin JSX y sin tocar renderer/. */
export const encendidoMeta: TransitionMeta = {
  id: 'encendido',
  name: 'Encendido de cabina',
  description: 'La nave despierta: primero el centro, luego los laterales y por último el techo.',
  from: 'nave-apagada',
  to: 'nave-encendida',
  accent: '#f2c230',
  looks: ['realista'],
  params: [
    {
      kind: 'number',
      key: 'durationMs',
      label: 'Duración',
      hint: 'Al terminar queda activa la animación de destino',
      group: 'Ritmo',
      min: 3000,
      max: 30000,
      step: 500,
      unit: ' ms',
      default: 11000,
    },
    {
      kind: 'number',
      key: 'ease',
      label: 'Arranque lento',
      hint: 'Cuánto se demora el principio antes de coger ritmo',
      group: 'Ritmo',
      min: 1,
      max: 4,
      step: 0.1,
      default: 2.4,
    },
    {
      kind: 'select',
      key: 'endMode',
      label: 'Estado al encender',
      group: 'Ritmo',
      options: [
        { value: 'calma', label: 'Calma' },
        { value: 'alerta', label: 'Alerta' },
      ],
      default: 'calma',
    },
    {
      kind: 'number',
      key: 'moonSize',
      label: 'Tamaño de la luna',
      group: 'Fuera',
      min: 0,
      max: 150,
      step: 2,
      default: 62,
    },
    {
      kind: 'number',
      key: 'starCount',
      label: 'Estrellas',
      group: 'Fuera',
      min: 0,
      max: 120,
      step: 2,
      default: 34,
    },
    {
      kind: 'boolean',
      key: 'fadeOut',
      label: 'Desvanecer el exterior al final',
      hint: 'Para destinos con otro cielo. Hacia «Nave encendida», apagado: la luna sigue ahí.',
      group: 'Fuera',
      default: false,
    },
  ],
}
