import type { AnimationMeta } from '../../shared/types'

/** Ficha de "Nave apagada". Datos puros: sin JSX y sin importar nada de renderer/. */
export const naveApagadaMeta: AnimationMeta = {
  id: 'nave-apagada',
  name: 'Nave apagada',
  description: 'Todo en silencio. La cabina a oscuras y, por la ventana, la luna y unas pocas estrellas quietas.',
  accent: '#8fa3bd',
  looks: ['realista'],
  params: [
    {
      kind: 'number',
      key: 'darkness',
      label: 'Oscuridad de la cabina',
      hint: 'Los huecos al exterior no se oscurecen',
      group: 'Cabina',
      min: 0,
      max: 1,
      step: 0.02,
      default: 0.86,
    },
    {
      kind: 'number',
      key: 'moonSize',
      label: 'Tamaño de la luna',
      group: 'Luna',
      min: 20,
      max: 150,
      step: 2,
      default: 62,
    },
    {
      kind: 'number',
      key: 'moonPhase',
      label: 'Fase',
      hint: '0 llena · 0,5 media · 1 nueva',
      group: 'Luna',
      min: 0,
      max: 1,
      step: 0.02,
      default: 0.26,
    },
    {
      kind: 'number',
      key: 'moonX',
      label: 'Posición horizontal',
      group: 'Luna',
      min: 0,
      max: 100,
      step: 1,
      unit: '%',
      default: 72,
    },
    {
      kind: 'number',
      key: 'moonY',
      label: 'Posición vertical',
      group: 'Luna',
      min: 0,
      max: 100,
      step: 1,
      unit: '%',
      default: 30,
    },
    {
      kind: 'boolean',
      key: 'moonCraters',
      label: 'Cráteres',
      group: 'Luna',
      default: true,
    },
    {
      kind: 'number',
      key: 'drift',
      label: 'Deriva',
      hint: 'La nave va a la deriva y la luna se desplaza. A 0 queda todo quieto.',
      group: 'Luna',
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.25,
    },
    {
      kind: 'number',
      key: 'starCount',
      label: 'Estrellas',
      group: 'Cielo',
      min: 0,
      max: 120,
      step: 2,
      default: 34,
    },
  ],
}
