import type { AnimationMeta } from '../../shared/types'
import { ACCENT } from '../../shared/palette'

/** Ficha de "Farol del planeta enano". Datos puros: sin JSX y sin importar nada de renderer/. */
export const farolEnanoMeta: AnimationMeta = {
  id: 'farol-enano',
  name: 'Farol del planeta enano',
  description: 'Fondo: un farol en lo alto de un planeta diminuto donde el día y la noche pasan volando.',
  accent: ACCENT.blue,
  looks: ['realista', 'diorama'],
  params: [
    {
      kind: 'select',
      key: 'mode',
      label: 'Día y noche',
      quick: true,
      group: 'Día y noche',
      options: [
        { value: 'auto', label: 'Ciclo' },
        { value: 'manual', label: 'Manual' },
      ],
      default: 'auto',
    },
    {
      kind: 'number',
      key: 'cycleSeconds',
      quick: true,
      label: 'Duración de cada ciclo',
      hint: 'Un día y una noche completos',
      group: 'Día y noche',
      showIf: { key: 'mode', equals: 'auto' },
      min: 4,
      max: 120,
      step: 1,
      unit: ' s',
      default: 20,
    },
    {
      kind: 'boolean',
      key: 'night',
      quick: true,
      label: 'Cambiar',
      hint: 'El cielo gira y el astro nuevo queda en el centro',
      group: 'Día y noche',
      showIf: { key: 'mode', equals: 'manual' },
      button: { toTrue: 'Hacer de noche', toFalse: 'Hacer de día' },
      default: false,
    },
    {
      kind: 'number',
      key: 'switchSeconds',
      label: 'Duración del cambio',
      group: 'Día y noche',
      showIf: { key: 'mode', equals: 'manual' },
      min: 0.4,
      max: 5,
      step: 0.1,
      unit: ' s',
      default: 1.6,
    },
    {
      kind: 'number',
      key: 'lightSize',
      label: 'Zona iluminada',
      hint: 'Cuánto suelo alumbra el farol de noche',
      group: 'Farol',
      min: 0.5,
      max: 1.8,
      step: 0.05,
      unit: 'x',
      default: 1,
    },
    {
      kind: 'boolean',
      key: 'moths',
      label: 'Bichitos alrededor de la luz',
      group: 'Farol',
      default: true,
    },
    {
      kind: 'boolean',
      key: 'bench',
      label: 'Banco',
      group: 'Farol',
      default: true,
    },
  ],
}
